#!/bin/sh
#
# Startup script for OpenDJ
#
# chkconfig: - 84 16
# description: OpenDJ
# processname: opensg
# pidfile: /var/run/opendj.pid
# config:
# resolve links - $0 may be a softlink
ARG0="$0"
while [ -h "$ARG0" ]; do
  ls=`ls -ld "$ARG0"`
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '/.*' > /dev/null; then
    ARG0="$link"
  else
    ARG0="`dirname $ARG0`/$link"
  fi
done
DIRNAME="`dirname $ARG0`"
PROGRAM="`basename $ARG0`"
while [ ".$1" != . ]
do
  case "$1" in
    --java-home )
        JAVA_HOME="$2"
        shift; shift;
        continue
    ;;
    --opendj-home )
        OPENDJ_HOME="$2"
        shift; shift;
        continue
    ;;
    --oipendj-pid )
        OPENDJ_PID="$2"
        shift; shift;
        continue
    ;;
    --opendj-user )
        OPENDJ_USER="$2"
        shift; shift;
        continue
    ;;
    * )
        break
    ;;
  esac
done
# OS specific support (must be 'true' or 'false').
cygwin=false;
darwin=false;
case "`uname`" in
    CYGWIN*)
        cygwin=true
        ;;
    Darwin*)
        darwin=true
        ;;
esac

# Use the maximum available, or set MAX_FD != -1 to use that
test ".$MAX_FD" = . && MAX_FD="maximum"
# Setup parameters for running the jsvc
#
test ".$OPENDJ_USER" = . && OPENDJ_USER=testmgr
# Set JAVA_HOME to working JDK or JRE
JAVA_HOME=/usr/java/default
# If not set we'll try to guess the JAVA_HOME
# from java binary if on the PATH
#
if [ -z "$JAVA_HOME" ]; then
    JAVA_BIN="`which java 2>/dev/null || type java 2>&1`"
    test -x "$JAVA_BIN" && JAVA_HOME="`dirname $JAVA_BIN`"
    test ".$JAVA_HOME" != . && JAVA_HOME=`cd "$JAVA_HOME/.." >/dev/null; pwd`
else
    JAVA_BIN="$JAVA_HOME/bin/java"
fi

OPENDJ_HOME=/home/${OPENDJ_USER}/OpenDJ
OPENDS_JAVA_ARGS=-Xmx2048m

# Increase the maximum file descriptors if we can
if [ "$cygwin" = "false" ]; then
    MAX_FD_LIMIT=`ulimit -H -n`
    if [ "$?" -eq 0 ]; then
        # Darwin does not allow RLIMIT_INFINITY on file soft limit
        if [ "$darwin" = "true" -a "$MAX_FD_LIMIT" = "unlimited" ]; then
            MAX_FD_LIMIT=`/usr/sbin/sysctl -n kern.maxfilesperproc`
        fi
        test ".$MAX_FD" = ".maximum" && MAX_FD="$MAX_FD_LIMIT"
        ulimit -n $MAX_FD
        if [ "$?" -ne 0 ]; then
            echo "$PROGRAM: Could not set maximum file descriptor limit: $MAX_FD"
        fi
    else
        echo "$PROGRAM: Could not query system maximum file descriptor limit: $MAX_FD_LIMIT"
    fi
fi

# ----- Execute The Requested Command -----------------------------------------
case "$1" in
    start   )
      su -m ${OPENDJ_USER} -c "${OPENDJ_HOME}/bin/start-ds -Q"
      RC=$?
      [ $RC = 0 ] && touch -f /var/lock/subsys/opendj
      exit $?
    ;;
    stop    )
      su -m ${OPENDJ_USER} -c "${OPENDJ_HOME}/bin/stop-ds -Q"
      RC=$?
      [ $RC = 0 ] && rm -f /var/lock/subsys/opendj
      exit $?
    ;;
    *       )
      echo "Unkown command: \`$1'"
      echo "Usage: $PROGRAM ( commands ... )"
      echo "commands:"
      echo "  start             Start OpenDJ"
      echo "  stop              Stop OpenDJ"
      exit 1
    ;;
esac
